clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:

  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.ivy2
      - ./.coursier
    volumes:
      - /tmp/cache:/cache
    when:
      event: [push, deployment, tag]

  fakes3:
    image: gwiq/fake-s3
    detach: true
    commands:
      - fakes3 -r /fakes3_root -p 4567
    when:
      event: push

  run-tests:
    image: gwiq/sbt-docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker:/root/.docker
    commands:
      - sbt -mem 1024 -Djline.terminal=off -Dcoursier.cache=./.coursier -Dsbt.ivy.home=./.ivy2 -Dfile.encoding=utf-8 -Dsbt.gigahorse=false test
    secrets:
    - source: staging_gcs_credentials
      target: google_application_credentials
    - source: aws_access_key_id
      target: aws_access_key_id
    - source: aws_secret_access_key
      target: aws_secret_access_key
    - source: aws_region
      target: aws_region
    when:
      event: push

  publish-maven-artifacts:
    image: gwiq/sbt-docker:latest
    commands:
      - sbt -mem 1024 -Djline.terminal=off -Dcoursier.cache=./.coursier -Dsbt.ivy.home=./.ivy2 -Dfile.encoding=utf-8 publish
    secrets:
      - source: bintray_user
        target: bintray_user
      - source: bintray_pass
        target: bintray_pass
      - source: aws_access_key_id
        target: aws_access_key_id
      - source: aws_secret_access_key
        target: aws_secret_access_key
      - source: aws_region
        target: aws_region
    when:
      event: [deployment, tag]

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.ivy2
      - ./.coursier
    volumes:
      - /tmp/cache:/cache
    when:
      event: [push, deployment, tag]
